name: Build & publish Docker image

on:
  push:
    paths:
      - 'Dockerfile'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and publish
        uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nitanmarcel/py3tg
          tags: latest
          tag_with_ref: true
          tag_with_sha: true